.

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -111,14 +111,16 @@ runs:
             exit 1
           fi
           FILES=$(jq -r .files[].filename __compare.json)
-          # Don't allow merge-ups when there are changes to dependencies
-          if [[ $(echo "$FILES" | grep composer.json) != "" ]] || \
-            [[ $(echo "$FILES" | grep package.json) != "" ]] || \
-            [[ $(echo "$FILES" | grep yarn.lock) != "" ]]
-          then
-            echo "Unable to mergeup between $FROM_BRANCH and $INTO_BRANCH - there are changes to dependencies"
-            exit 1
-          fi
+          
+          # Don't allow merge-ups when there are changes in dependency files
+          DEPENDENCY_FILES="composer.json package.json yarn.lock"
+          for DEPENDENCY_FILE in $DEPENDENCY_FILES; do
+            if [[ $(echo "$FILES" | grep $DEPENDENCY_FILE) != "" ]]; then
+              echo "Unable to mergeup between $FROM_BRANCH and $INTO_BRANCH - there are changes in $DEPENDENCY_FILE"
+              exit 1
+            fi
+          done
+
           # Don't allow merge-ups when there are JS changes that would require a yarn build
           if [[ $(echo "$FILES" | grep client/) != "" ]]; then
             echo "Unable to mergeup between $FROM_BRANCH and $INTO_BRANCH - there are changes to JS files"
